#!/bin/bash

function checkpandoc(){
  TEST=$(which pandoc)
  if [[ -z "$TEST" ]]; then
    echo "ERROR: 'pandoc' command not found. Install 'pandoc' first, e.g. 'brew install pandoc'."
    exit -1
  fi
}

function usage(){
  NAME=$(basename $0)
  echo "Usage: $NAME <filename>"
}

if [[ -z $1 ]]; then
  usage && exit -1
fi

checkpandoc
pandoc -t plain "$1" | less
